# Generated by Django 6.0.6 on 2026-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='corrected_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
